---
title: "Assignment 3- Compmod + Sockult exam"
author: "Alba Gonzalez Herrero and Astrid Kjær Olling"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(brms)
library(rethinking)
library(bayesplot)
```


### PRE-PROCESSING

```{r}
knitr::opts_chunk$set(echo = TRUE)

df = read_csv("/Users/al/RStudio👩🏻‍💻/Semester 4/Computational modeling for CogSci/EXAM/Exam/HerrmannThoeniGaechterDATA.csv")

#Deleting NA rows

df <- df[-c(1, 2),]

#Making first row as header

names(df) <- as.matrix(df[1, ])
df <- df[-1, ]

```

```{r}

#Creating column overall contribution with mean values

df$senderscontribution <- as.numeric(df$senderscontribution)

df2 <- df %>%                                        # Specify data frame
  group_by(subjectid, p) %>%                         # Specify group indicator
  summarise_at(vars(senderscontribution),              # Specify column
               list(overall_contr = mean))                # Specify function

df <- merge(x=df, y= df2, by.x= c("subjectid", "p"), by.y = c("subjectid", "p"))


#Creating a colum for GEI values

#Creating column with NAs
df$GEI <- c(NA)

#Mutating GEI column to add GEI values for all countries depending on city column 
df <- df %>% mutate(GEI =
                  case_when(city== "Samara" ~ 76,
                           city== "Minsk" ~ 66,
                           city== "Boston" ~ 75,
                           city== "Muscat"~ 48,
                           city== "St. Gallen"~ 63,
                           city== "Copenhagen"~ 80,
                           city== "Nottingham"~ 75,
                           city== "Zurich"~ 63,
                           city== "Dnipropetrovs'k"~ 74,
                           city== "Riyadh"~ 47,
                           city== "Istanbul"~ 46,
                           city== "Chengdu"~ 69,
                           city== "Seoul"~ 54,
                           city== "Bonn"~ 80,
                           city== "Athens"~ 66,
                           city== "Melbourne"~ 76,
                           ))

```

```{r}

#Creating a new dataset with only the variables we will use

df <- subset(df, select=c(subjectid, groupid,female, city, p, overall_contr, GEI, punishment))

#Creating a df and subsetting necessary variables for the second model on punishment and forgiveness

dfpun <- subset(df, select=c(subjectid, groupid,female, city, p, GEI, punishment))
dfpun$punishment <- as.numeric(dfpun$punishment)

#Deleting all N-experiment data

df<-df[!(df$p=="N-experiment"),]
dfpun<-dfpun[!(dfpun$p=="N-experiment"),]


#Creating a column for overall punishment given to other teammates per participant

df3 <- dfpun %>%                                        # Specify data frame
  group_by(subjectid) %>%                         # Specify group indicator
  summarise_at(vars(punishment),              # Specify column
               list(overall_punishment = sum)) 
dfpun <- merge(x=dfpun, y= df3, by.x= c("subjectid"), by.y = c("subjectid"))

#Removing duplicate rows in dfpun

dfpun <- subset(dfpun, select=c(subjectid, groupid,female, city, p, GEI, overall_punishment))

dfpun <- distinct(dfpun)

#Creating a new dataset with only the variables we will use

df <- subset(df, select=c(subjectid, groupid,female, city, p, overall_contr, GEI))

#Removing all the duplicate rows

df <- distinct(df)

```



  ##### BAYESIAN WORKFLOW #####

```{r}
#Standardizing variables to make priors easier to set

df= df %>% mutate(
  overall_contr_st = standardize(overall_contr),
  GEI_st = standardize(GEI)
)

dfpun = dfpun %>% mutate(
  overall_punishment_st = standardize(overall_punishment),
  GEI_st = standardize(GEI)
)

```

  
```{r}

  ###  MODEL 1  ###


df$female <- as.factor(df$female)


  #MODEL 1

m1 = bf(overall_contr_st ~ 0 + female +(1|subjectid)+(1|GEI_st))


#Priors

get_prior(m1, family = gaussian, data = df)


prior_m1 = c(
  prior(normal(0,1), class = b, coef = female0),
  prior(normal(0,1), class = b, coef = female1),
  prior(normal(0,1), class = sd, group = subjectid),
  prior(normal(0,1), class = sd, group = GEI_st),
  prior(normal(1,0.5), class = sigma)
)

m1_prior = brm(
  m1,
  df,
  family = "skew_normal",
  prior = prior_m1,
  sample_prior = "only",  
  file = "prior_m1",
    control=list(
    adapt_delta = 0.99,
    max_treedepth = 20)
)

summary(m1_prior)


#Doing prior predictive check    

pp_check(m1_prior, nsamples = 100)


#Checking trace and rank plots

mcmc_trace(m1_prior, pars = "b_female1")
mcmc_trace(m1_prior, pars= "b_female0")
mcmc_rank_overlay(m1_prior, pars = "b_female1")
mcmc_rank_overlay(m1_prior, pars = "b_female0")

```



```{r}

#Posterior checks

m1_post = brm(
  m1,
  df,
  family = "skew_normal",
  prior = prior_m1,
  sample_prior = T,  
  file = "m1",
    control=list(
    adapt_delta = 0.99,
    max_treedepth = 20)
)

pp_check(m1_post, nsamples = 100)

#Prior-posterior update plots

posterior_m1 = posterior_samples(m1_post)

ggplot(posterior_m1) +
  theme_classic() +
  geom_density(aes(b_female1), fill="red", alpha=0.3) +
  geom_density(aes(prior_b_female1), fill="blue", alpha=0.5)

ggplot(posterior_m1) +
  theme_classic() +
  geom_density(aes(b_female0), fill="red", alpha=0.3) +
  geom_density(aes(prior_b_female0), fill="blue", alpha=0.5)

ggplot(posterior_m1) +
  theme_classic() +
  geom_density(aes(posterior$sd_GEI_st__Intercept), fill="red", alpha=0.3) +
  geom_density(aes(posterior$prior_sd_GEI_st), fill="blue", alpha=0.5)

ggplot(posterior_m1) +
  theme_classic() +
  geom_density(aes(posterior$sd_subjectid__Intercept), fill="red", alpha=0.3) +
  geom_density(aes(posterior$prior_sd_subjectid), fill="blue", alpha=0.5)

ggplot(posterior_m1) +
  theme_classic() +
  geom_density(aes(posterior$sigma), fill="red", alpha=0.3) +
  geom_density(aes(posterior$prior_sigma), fill="blue", alpha=0.5)


```

```{r}
  ###  MODEL 2 ###

dfpun$female <- as.factor(dfpun$female)

m2 = bf(overall_punishment_st ~ 0 + female +(1|subjectid)+(1|GEI_st))


get_prior(m2, family = gaussian, data = dfpun)


prior_m2 = c(
  prior(normal(0,1), class = b, coef = female0),
  prior(normal(0,1), class = b, coef = female1),
  prior(normal(0,1), class = sd, group = subjectid),
  prior(normal(0,1), class = sd, group = GEI_st),
  prior(normal(1,0.5), class = sigma)
)

m2_prior = brm(
  m2,
  dfpun,
  family = gaussian(),
  prior = prior_m2,
  sample_prior = "only",  
  file = "prior_m2",
    control=list(
    adapt_delta = 0.99,
    max_treedepth = 20)
)

summary(m2_prior)

pp_check(m2_prior, nsamples = 100)

m2_post = brm(
  m2,
  dfpun,
  family = gaussian(),
  prior = prior_m2,
  sample_prior = T,  
  file = "m2",
  control=list(
    adapt_delta = 0.99,
    max_treedepth = 20),
  iter= 2500
)

pp_check(m2_post, nsamples = 100)

#Posterior samples

posterior_m2 = posterior_samples(m2_post)

#Prior posterior update plots

ggplot(posterior_m2) +
  theme_classic() +
  geom_density(aes(posterior$sd_GEI_st__Intercept), fill="red", alpha=0.3) +
  geom_density(aes(posterior$prior_sd_GEI_st), fill="blue", alpha=0.5)

ggplot(posterior_m2) +
  theme_classic() +
  geom_density(aes(b_female1), fill="red", alpha=0.3) +
  geom_density(aes(prior_b_female1), fill="blue", alpha=0.5)

ggplot(posterior_m2) +
  theme_classic() +
  geom_density(aes(b_female0), fill="red", alpha=0.3) +
  geom_density(aes(prior_b_female0), fill="blue", alpha=0.5)

ggplot(posterior_m2) +
  theme_classic() +
  geom_density(aes(posterior$sd_subjectid__Intercept), fill="red", alpha=0.3) +
  geom_density(aes(posterior$prior_sd_subjectid), fill="blue", alpha=0.5)

ggplot(posterior_m2) +
  theme_classic() +
  geom_density(aes(sigma), fill="red", alpha=0.3) +
  geom_density(aes(prior_sigma), fill="blue", alpha=0.5)

#Rank and trace plots

mcmc_trace(m2_prior, pars = "b_female1")
mcmc_trace(m2_prior, pars= "b_female0")
mcmc_rank_overlay(m2_prior, pars = "b_female1")
mcmc_rank_overlay(m2_prior, pars = "b_female0")

``` 
  